version: "3.1"

volumes:
    logs:
        driver: local

services:

    mysql:
        image: mysql:5.6
        container_name: desafio-mysql
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=desafio_pagarme
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=1234
        ports:
            - "3306:3306"

    webserver:
        image: nginx:alpine
        container_name: desafio-webserver
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php-fpm:
        build: phpdocker/php-fpm
        container_name: desafio-php-fpm
        working_dir: /var/www
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
            - ~/.ssh/:/root/.ssh
        stdin_open: true
        tty: true